# Generated by Django 5.2.13 on 2026-06-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldguideitem',
            name='cons',
            field=models.JSONField(blank=True, default=list, help_text='JSON formatında başlık ve açıklama listesi. Örnek: [{"title": "Dezavantaj Başlığı", "desc": "Detaylı açıklama..."}]', verbose_name='Dezavantajlar (Üretim Modelleri İçin)'),
        ),
        migrations.AlterField(
            model_name='fieldguideitem',
            name='preventative_measures',
            field=models.JSONField(blank=True, default=list, help_text='Köşeli parantez içinde, her madde çift tırnaklı bir metin olacak şekilde liste yazın. Örnek: ["Önlem 1", "Önlem 2"]', verbose_name='Önleyici Tedbirler (Liste)'),
        ),
        migrations.AlterField(
            model_name='fieldguideitem',
            name='pros',
            field=models.JSONField(blank=True, default=list, help_text='JSON formatında başlık ve açıklama listesi. Örnek: [{"title": "Avantaj Başlığı", "desc": "Detaylı açıklama..."}]', verbose_name='Avantajlar (Üretim Modelleri İçin)'),
        ),
        migrations.AlterField(
            model_name='fieldguideitem',
            name='symptoms',
            field=models.JSONField(blank=True, default=list, help_text='Köşeli parantez içinde, her madde çift tırnaklı bir metin olacak şekilde liste yazın. Örnek: ["Belirti 1", "Belirti 2"]', verbose_name='Klinik Belirtiler (Liste)'),
        ),
    ]
