# Generated by Django 5.2.13 on 2026-06-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fieldguideitem_cons_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldGuideItem',
        ),
    ]
