# Generated by Django 5.2.13 on 2026-04-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Bitki Adı (Örn: Domates)')),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Bilimsel Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Genel Bilgi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
            ],
            options={
                'verbose_name': 'Bitki',
                'verbose_name_plural': 'Bitkiler',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Hastalık Adı (Örn: Erken Yanıklık)')),
                ('symptoms', models.TextField(verbose_name='Belirtiler')),
                ('organic_treatment', models.TextField(blank=True, null=True, verbose_name='Organik Çözüm')),
                ('chemical_treatment', models.TextField(blank=True, null=True, verbose_name='Kimyasal Çözüm')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='Önlem ve Tavsiyeler')),
                ('ai_class_id', models.IntegerField(blank=True, null=True, verbose_name='Yapay Zeka Sınıf ID (Opsiyonel)')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='encyclopedia.plant', verbose_name='Ait Olduğu Bitki')),
            ],
            options={
                'verbose_name': 'Hastalık',
                'verbose_name_plural': 'Hastalıklar',
            },
        ),
    ]
