# Generated by Django 5.2.13 on 2026-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('Sebzeler', 'Sebzeler'), ('Meyveler', 'Meyveler'), ('Tahıllar', 'Tahıllar'), ('Baharat & Otlar', 'Baharat & Otlar'), ('Diğer', 'Diğer')], default='Diğer', max_length=50, verbose_name='Kategori'),
        ),
    ]
