# Generated by Django 5.2.13 on 2026-04-08 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='community/posts/', verbose_name='Tarla/Yaprak Fotoğrafı')),
                ('content', models.TextField(verbose_name='Soru veya Paylaşım')),
                ('is_solved', models.BooleanField(default=False, verbose_name='Çözüme Kavuştu mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Paylaşım Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.farmerprofile', verbose_name='Çiftçi/Yazar')),
                ('related_plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.plant', verbose_name='İlgili Bitki Etiketi')),
            ],
            options={
                'verbose_name': 'Köy Meydanı Gönderisi',
                'verbose_name_plural': 'Köy Meydanı Gönderileri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yorum/Tavsiye')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_expert_advice', models.BooleanField(default=False, verbose_name='Uzman Tavsiyesi mi?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.farmerprofile', verbose_name='Yorum Yapan')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post', verbose_name='İlgili Gönderi')),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['created_at'],
            },
        ),
    ]
