# Generated by Django 5.2.13 on 2026-05-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='community/posts/', verbose_name='Tarla/Yaprak Fotoğrafı'),
        ),
    ]
