# Generated by Django 5.2.13 on 2026-04-08 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bölge/Şehir')),
                ('experience_level', models.CharField(choices=[('newbie', 'Yeni Başlayan'), ('experienced', 'Deneyimli Çiftçi'), ('expert', 'Ziraat Uzmanı')], default='newbie', max_length=20, verbose_name='Deneyim Seviyesi')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Çiftçi Profili',
                'verbose_name_plural': 'Çiftçi Profilleri',
            },
        ),
    ]
