# Generated by Django 5.2.13 on 2026-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkımda (Kısa Biyografi)'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='grown_plants',
            field=models.ManyToManyField(blank=True, to='encyclopedia.plant', verbose_name='Yetiştirdiğim Bitkiler'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Konum (İl/İlçe)'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profil Fotoğrafı'),
        ),
    ]
