# Generated by Django 5.2.13 on 2026-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_farmerprofile_created_at_and_more'),
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='favorite_plants',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='encyclopedia.plant', verbose_name='Favori Bitkilerim'),
        ),
    ]
