# Generated by Django 5.2.13 on 2026-05-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmerprofile_favorite_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Kapak Fotoğrafı'),
        ),
    ]
