# Generated by Django 5.2.13 on 2026-04-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='diagnostics/original/', verbose_name='Yüklenen Fotoğraf')),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='diagnostics/heatmaps/', verbose_name='XAI Isı Haritası')),
                ('confidence_score', models.FloatField(verbose_name='Güven Skoru (%)')),
                ('is_user_verified', models.BooleanField(default=False, verbose_name='Kullanıcı Doğruladı mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Teşhis Tarihi')),
                ('detected_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.disease', verbose_name='Teşhis Edilen Hastalık')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.farmerprofile')),
            ],
            options={
                'verbose_name': 'Teşhis Raporu',
                'verbose_name_plural': 'Teşhis Raporları',
            },
        ),
    ]
