# Generated by Django 5.2.13 on 2026-05-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIPLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Adresi')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('tokens', models.IntegerField(default=50, verbose_name='Kalan Token')),
            ],
            options={
                'verbose_name': 'Misafir IP Limiti',
                'verbose_name_plural': 'Misafir IP Limitleri',
                'unique_together': {('ip_address', 'date')},
            },
        ),
    ]
