# Generated by Django 5.2.13 on 2026-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldGuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('scientific_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Bilimsel Adı')),
                ('category', models.CharField(max_length=100, verbose_name='Kategori')),
                ('season', models.CharField(max_length=50, verbose_name='Dönem/Mevsim')),
                ('risk_level', models.CharField(max_length=50, verbose_name='Risk Seviyesi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='Köşeli parantez içinde, her madde çift tırnaklı bir metin olacak şekilde liste yazın. Örnek: ["Belirti 1", "Belirti 2"]', verbose_name='Klinik Belirtiler (Liste)')),
                ('favorable_conditions', models.TextField(verbose_name='Tetikleyici Çevresel Koşullar')),
                ('case_scenario', models.TextField(verbose_name='Saha Vaka Raporu')),
                ('organic_recipe_name', models.CharField(max_length=200, verbose_name='Organik Reçete Adı')),
                ('organic_recipe_prep', models.TextField(verbose_name='Reçete Hazırlanışı')),
                ('organic_recipe_app', models.TextField(verbose_name='Sahada Uygulanışı')),
                ('preventative_measures', models.JSONField(blank=True, default=list, help_text='Köşeli parantez içinde, her madde çift tırnaklı bir metin olacak şekilde liste yazın. Örnek: ["Önlem 1", "Önlem 2"]', verbose_name='Önleyici Tedbirler (Liste)')),
                ('recipe_preview', models.TextField(blank=True, null=True, verbose_name='Kısa Reçete Önizlemesi (Kartlar İçin)')),
                ('pros', models.JSONField(blank=True, default=list, help_text='JSON formatında başlık ve açıklama listesi. Örnek: [{"title": "Avantaj Başlığı", "desc": "Detaylı açıklama..."}]', verbose_name='Avantajlar (Üretim Modelleri İçin)')),
                ('cons', models.JSONField(blank=True, default=list, help_text='JSON formatında başlık ve açıklama listesi. Örnek: [{"title": "Dezavantaj Başlığı", "desc": "Detaylı açıklama..."}]', verbose_name='Dezavantajlar (Üretim Modelleri İçin)')),
            ],
            options={
                'verbose_name': 'Ziraat Rehberi İçeriği',
                'verbose_name_plural': 'Ziraat Rehberi İçerikleri',
                'ordering': ['id'],
            },
        ),
    ]
